name = "changeset-adiffs-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
minify = false

[observability]
enabled = true # turn on logging

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "osm-augmented-diffs"
preview_bucket_name = "osm-augmented-diffs"

[[queues.consumers]]
queue = "changeset-adiffs"
# max_batch_size = 100 # optional
# max_batch_timeout = 30 # optional
